soft-fail: true  # Module repo: report findings but don't block CI
framework:
  - terraform

skip-check:
  # False positive: EIP is attached to NAT Gateway, not EC2
  - CKV2_AWS_19
  # False positive: Security group is attached via module reference
  - CKV2_AWS_5
  # Server private keys don't rotate automatically
  - CKV2_AWS_57
  # Using Terraform Registry with version constraints
  - CKV_TF_1
  - CKV_TF_2
  # Secrets Manager uses AWS-managed encryption by default
  - CKV_AWS_149
  # Lambda function URL is intentionally public (Discord webhook)
  - CKV_AWS_301
  # KMS policy allows service principals by design
  - CKV_AWS_63
  - CKV_AWS_62
  - CKV_AWS_356
  - CKV_AWS_283
  # Admin module intentionally grants admin access
  - CKV_AWS_274
  # IAM assume role policies are correctly scoped
  - CKV_AWS_60
  - CKV_AWS_61
  # False positive on provider block
  - CKV_AWS_41
  # KMS policy allows root account (AWS best practice for key admin)
  - CKV_AWS_111
  - CKV_AWS_109
