# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      Environment = "prod"
      ManagedBy   = "terragrunt"
      Project     = "tradewitme"
    }
  }
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"

  default_tags {
    tags = {
      Environment = "prod"
      ManagedBy   = "terragrunt"
      Project     = "tradewitme"
    }
  }
}

provider "aws" {
  alias  = "us-east-2"
  region = "us-east-2"

  default_tags {
    tags = {
      Environment = "prod"
      ManagedBy   = "terragrunt"
      Project     = "tradewitme"
    }
  }
}
