# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "tradewitme-prod-tf-state-us-east-1"
    encrypt      = true
    key          = "tradewitme-live/prod/networking/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
